# Generated by Django 4.0.6 on 2022-07-23 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_alter_user_gender_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
